version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html   # Altere aqui para a raiz do projeto
    networks:
      - app-network

networks:
  app-network:
    driver: bridge